In [3]:
###########################
# Look Test Data
###########################
import pandas as pd

df = pd.read_csv('./Test.csv',header= 0)
df.head(15)

    Width  Height  Roi.X1  Roi.Y1  Roi.X2  Roi.Y2  ClassId            Path
0      53      54       6       5      48      49       16  Test/00000.png
1      42      45       5       5      36      40        1  Test/00001.png
2      48      52       6       6      43      47       38  Test/00002.png
3      27      29       5       5      22      24       33  Test/00003.png
4      60      57       5       5      55      52       11  Test/00004.png
5      52      56       5       5      47      51       38  Test/00005.png
6     147     130      12      12     135     119       18  Test/00006.png
7      32      33       5       5      26      28       12  Test/00007.png
8      45      50       6       5      40      45       25  Test/00008.png
9      81      86       7       7      74      79       35  Test/00009.png
10     38      37       6       5      33      32       12  Test/00010.png
11     45      44       6       5      40      39        7  Test/00011.png
12     79      73       7       7      72      67       23  Test/00012.png
13     36      37       5       6      31      32        7  Test/00013.png
14     43      41       5       5      37      36        4  Test/00014.png

In [4]:
##############################
# Generate Test Data
##############################
import re
import glob 
import os
import shutil

taille = len(df['Path'])
mycolumns = ['ClassId','Path']
liste = []
tupl = ()
for i in range(taille):
        p = df['Path'][i]
        c = df['ClassId'][i]
        p = re.sub('.*\/', '', p)
        tupl = (int(c),p)
        liste.append(tupl)

for filepath in glob.iglob('./Test/*.png'):
        filepath = re.sub('.*\/', '', filepath)
        for x in liste:         
                if filepath in x:
                        if not os.path.exists(f'./Test/{str(x[0])}'):
                                path = os.path.join('./Test/',str(x[0]))
                                os.mkdir(path)
                        shutil.move(f'./Test/{x[1]}',f'./Test/{str(x[0])}')